---
ansible_host: mx1.pslab
interfaces_ebgp:
  xe-0/0/0:
    description: qfx10k-1 xe-0/0/0:1
    address: 192.168.0.0/31
    peer: qfx10k-1
    peer_interface: xe-0/0/0:1
  xe-0/0/3:
    description: qfx10k-2 xe-0/0/0:1
    address: 192.168.0.2/31
    peer: qfx10k-2
    peer_interface: xe-0/0/0:1
bgp:
  underlay_as: 4210000001
lo0:
  address: 10.0.0.1