---
ansible_host: qfx2.pslab
interfaces_ebgp:
  et-0/0/48:
    description: qfx10k-2 et-0/0/7
    address: 192.168.0.15/31
    peer: qfx10k-2
    peer_interface: et-0/0/7
  et-0/0/49:
    description: qfx10k-1 et-0/0/7
    address: 192.168.0.11/31
    peer: qfx10k-1
    peer_interface: et-0/0/7
bgp:
  underlay_as: 4210000004
lo0:
  address: 10.0.0.4
