---
- name: Gather facts from Junos devices
  hosts: junos
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars:
    tmp_dir: "work/tmp"
    conf_file: "{{ tmp_dir }}/{{ inventory_hostname }}.conf"
    connection_settings:
      host: "{{ ansible_host }}"
      ssh_config: ~/.ssh/config.d/pslab-quincy
    playbook_name: fabric-config.yml

  tasks:
    - name: confirm or create configs directory
      file:
        path: "{{ tmp_dir }}"
        state: directory
      run_once: yes

    - name: save device information using template
      template:
        src: base-settings.j2
        dest: "{{ conf_file }}"

    - name: Configure devices
      juniper_junos_config:
        provider: "{{ connection_settings }}"
        load: replace
        comment: "playbook {{ playbook_name }}, playbook with nameserver.conf file"
        confirmed: 5
        src: "{{ conf_file }}"
        diff: yes
        ignore_warning: yes
      register: config_results
      notify: confirm previous commit

    - name: show configuration change
      debug: var=config_results.diff_lines
      when: config_results.diff_lines is defined

    - name: delete generated configuration file
      file:
        path: "{{ conf_file }}"
        state: absent

  handlers:
    - name: confirm previous commit
      juniper_junos_config:
        provider: "{{ connection_settings }}"
        comment: "playbook {{ playbook_name }}, confirming previous commit"
        commit: yes
        diff: no



